// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.1
// source: proto/paigram/v1/bot_auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bot 类型
type BotType int32

const (
	BotType_BOT_TYPE_UNSPECIFIED BotType = 0
	BotType_BOT_TYPE_TELEGRAM    BotType = 1
	BotType_BOT_TYPE_DISCORD     BotType = 2
	BotType_BOT_TYPE_QQ          BotType = 3
	BotType_BOT_TYPE_WECHAT      BotType = 4
	BotType_BOT_TYPE_OTHER       BotType = 99
)

// Enum value maps for BotType.
var (
	BotType_name = map[int32]string{
		0:  "BOT_TYPE_UNSPECIFIED",
		1:  "BOT_TYPE_TELEGRAM",
		2:  "BOT_TYPE_DISCORD",
		3:  "BOT_TYPE_QQ",
		4:  "BOT_TYPE_WECHAT",
		99: "BOT_TYPE_OTHER",
	}
	BotType_value = map[string]int32{
		"BOT_TYPE_UNSPECIFIED": 0,
		"BOT_TYPE_TELEGRAM":    1,
		"BOT_TYPE_DISCORD":     2,
		"BOT_TYPE_QQ":          3,
		"BOT_TYPE_WECHAT":      4,
		"BOT_TYPE_OTHER":       99,
	}
)

func (x BotType) Enum() *BotType {
	p := new(BotType)
	*p = x
	return p
}

func (x BotType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BotType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_paigram_v1_bot_auth_proto_enumTypes[0].Descriptor()
}

func (BotType) Type() protoreflect.EnumType {
	return &file_proto_paigram_v1_bot_auth_proto_enumTypes[0]
}

func (x BotType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BotType.Descriptor instead.
func (BotType) EnumDescriptor() ([]byte, []int) {
	return file_proto_paigram_v1_bot_auth_proto_rawDescGZIP(), []int{0}
}

// Bot 状态
type BotStatus int32

const (
	BotStatus_BOT_STATUS_UNSPECIFIED BotStatus = 0
	BotStatus_BOT_STATUS_ACTIVE      BotStatus = 1
	BotStatus_BOT_STATUS_INACTIVE    BotStatus = 2
	BotStatus_BOT_STATUS_SUSPENDED   BotStatus = 3
	BotStatus_BOT_STATUS_REVOKED     BotStatus = 4
)

// Enum value maps for BotStatus.
var (
	BotStatus_name = map[int32]string{
		0: "BOT_STATUS_UNSPECIFIED",
		1: "BOT_STATUS_ACTIVE",
		2: "BOT_STATUS_INACTIVE",
		3: "BOT_STATUS_SUSPENDED",
		4: "BOT_STATUS_REVOKED",
	}
	BotStatus_value = map[string]int32{
		"BOT_STATUS_UNSPECIFIED": 0,
		"BOT_STATUS_ACTIVE":      1,
		"BOT_STATUS_INACTIVE":    2,
		"BOT_STATUS_SUSPENDED":   3,
		"BOT_STATUS_REVOKED":     4,
	}
)

func (x BotStatus) Enum() *BotStatus {
	p := new(BotStatus)
	*p = x
	return p
}

func (x BotStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BotStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_paigram_v1_bot_auth_proto_enumTypes[1].Descriptor()
}

func (BotStatus) Type() protoreflect.EnumType {
	return &file_proto_paigram_v1_bot_auth_proto_enumTypes[1]
}

func (x BotStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BotStatus.Descriptor instead.
func (BotStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_paigram_v1_bot_auth_proto_rawDescGZIP(), []int{1}
}

// Bot 信息
type Bot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          BotType                `protobuf:"varint,4,opt,name=type,proto3,enum=paigram.v1.BotType" json:"type,omitempty"`
	Status        BotStatus              `protobuf:"varint,5,opt,name=status,proto3,enum=paigram.v1.BotStatus" json:"status,omitempty"`
	Scopes        []string               `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastActiveAt  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bot) Reset() {
	*x = Bot{}
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bot) ProtoMessage() {}

func (x *Bot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bot.ProtoReflect.Descriptor instead.
func (*Bot) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_bot_auth_proto_rawDescGZIP(), []int{0}
}

func (x *Bot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Bot) GetType() BotType {
	if x != nil {
		return x.Type
	}
	return BotType_BOT_TYPE_UNSPECIFIED
}

func (x *Bot) GetStatus() BotStatus {
	if x != nil {
		return x.Status
	}
	return BotStatus_BOT_STATUS_UNSPECIFIED
}

func (x *Bot) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *Bot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Bot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Bot) GetLastActiveAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActiveAt
	}
	return nil
}

// Bot 注册请求
type RegisterBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type          BotType                `protobuf:"varint,3,opt,name=type,proto3,enum=paigram.v1.BotType" json:"type,omitempty"`
	Scopes        []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	OwnerEmail    string                 `protobuf:"bytes,5,opt,name=owner_email,json=ownerEmail,proto3" json:"owner_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBotRequest) Reset() {
	*x = RegisterBotRequest{}
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBotRequest) ProtoMessage() {}

func (x *RegisterBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBotRequest.ProtoReflect.Descriptor instead.
func (*RegisterBotRequest) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_bot_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterBotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterBotRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterBotRequest) GetType() BotType {
	if x != nil {
		return x.Type
	}
	return BotType_BOT_TYPE_UNSPECIFIED
}

func (x *RegisterBotRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *RegisterBotRequest) GetOwnerEmail() string {
	if x != nil {
		return x.OwnerEmail
	}
	return ""
}

// Bot 注册响应
type RegisterBotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bot           *Bot                   `protobuf:"bytes,1,opt,name=bot,proto3" json:"bot,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiSecret     string                 `protobuf:"bytes,3,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBotResponse) Reset() {
	*x = RegisterBotResponse{}
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBotResponse) ProtoMessage() {}

func (x *RegisterBotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBotResponse.ProtoReflect.Descriptor instead.
func (*RegisterBotResponse) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_bot_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterBotResponse) GetBot() *Bot {
	if x != nil {
		return x.Bot
	}
	return nil
}

func (x *RegisterBotResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *RegisterBotResponse) GetApiSecret() string {
	if x != nil {
		return x.ApiSecret
	}
	return ""
}

// Bot 登录请求
type BotLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiSecret     string                 `protobuf:"bytes,2,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotLoginRequest) Reset() {
	*x = BotLoginRequest{}
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotLoginRequest) ProtoMessage() {}

func (x *BotLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotLoginRequest.ProtoReflect.Descriptor instead.
func (*BotLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_bot_auth_proto_rawDescGZIP(), []int{3}
}

func (x *BotLoginRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *BotLoginRequest) GetApiSecret() string {
	if x != nil {
		return x.ApiSecret
	}
	return ""
}

// Bot 登录响应
type BotLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	TokenType     string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Bot           *Bot                   `protobuf:"bytes,5,opt,name=bot,proto3" json:"bot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotLoginResponse) Reset() {
	*x = BotLoginResponse{}
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotLoginResponse) ProtoMessage() {}

func (x *BotLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotLoginResponse.ProtoReflect.Descriptor instead.
func (*BotLoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_bot_auth_proto_rawDescGZIP(), []int{4}
}

func (x *BotLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *BotLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *BotLoginResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *BotLoginResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *BotLoginResponse) GetBot() *Bot {
	if x != nil {
		return x.Bot
	}
	return nil
}

// 刷新令牌请求
type RefreshBotTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshBotTokenRequest) Reset() {
	*x = RefreshBotTokenRequest{}
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshBotTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshBotTokenRequest) ProtoMessage() {}

func (x *RefreshBotTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshBotTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshBotTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_bot_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshBotTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// 刷新令牌响应
type RefreshBotTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	TokenType     string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshBotTokenResponse) Reset() {
	*x = RefreshBotTokenResponse{}
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshBotTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshBotTokenResponse) ProtoMessage() {}

func (x *RefreshBotTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshBotTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshBotTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_bot_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshBotTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshBotTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshBotTokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *RefreshBotTokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

// 验证令牌请求
type ValidateBotTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateBotTokenRequest) Reset() {
	*x = ValidateBotTokenRequest{}
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateBotTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateBotTokenRequest) ProtoMessage() {}

func (x *ValidateBotTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateBotTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateBotTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_bot_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateBotTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// 验证令牌响应
type ValidateBotTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Bot           *Bot                   `protobuf:"bytes,2,opt,name=bot,proto3" json:"bot,omitempty"`
	Scopes        []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateBotTokenResponse) Reset() {
	*x = ValidateBotTokenResponse{}
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateBotTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateBotTokenResponse) ProtoMessage() {}

func (x *ValidateBotTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateBotTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateBotTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_bot_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateBotTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateBotTokenResponse) GetBot() *Bot {
	if x != nil {
		return x.Bot
	}
	return nil
}

func (x *ValidateBotTokenResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ValidateBotTokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// 撤销令牌请求
type RevokeBotTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeBotTokenRequest) Reset() {
	*x = RevokeBotTokenRequest{}
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeBotTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeBotTokenRequest) ProtoMessage() {}

func (x *RevokeBotTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeBotTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeBotTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_bot_auth_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeBotTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// 撤销令牌响应
type RevokeBotTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeBotTokenResponse) Reset() {
	*x = RevokeBotTokenResponse{}
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeBotTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeBotTokenResponse) ProtoMessage() {}

func (x *RevokeBotTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeBotTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeBotTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_bot_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeBotTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RevokeBotTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取 Bot 信息请求
type GetBotInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotInfoRequest) Reset() {
	*x = GetBotInfoRequest{}
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotInfoRequest) ProtoMessage() {}

func (x *GetBotInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotInfoRequest.ProtoReflect.Descriptor instead.
func (*GetBotInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_bot_auth_proto_rawDescGZIP(), []int{11}
}

func (x *GetBotInfoRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

// 获取 Bot 信息响应
type GetBotInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bot           *Bot                   `protobuf:"bytes,1,opt,name=bot,proto3" json:"bot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotInfoResponse) Reset() {
	*x = GetBotInfoResponse{}
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotInfoResponse) ProtoMessage() {}

func (x *GetBotInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paigram_v1_bot_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotInfoResponse.ProtoReflect.Descriptor instead.
func (*GetBotInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_paigram_v1_bot_auth_proto_rawDescGZIP(), []int{12}
}

func (x *GetBotInfoResponse) GetBot() *Bot {
	if x != nil {
		return x.Bot
	}
	return nil
}

var File_proto_paigram_v1_bot_auth_proto protoreflect.FileDescriptor

const file_proto_paigram_v1_bot_auth_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/paigram/v1/bot_auth.proto\x12\n" +
	"paigram.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf3\x02\n" +
	"\x03Bot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.paigram.v1.BotTypeR\x04type\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.paigram.v1.BotStatusR\x06status\x12\x16\n" +
	"\x06scopes\x18\x06 \x03(\tR\x06scopes\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12@\n" +
	"\x0elast_active_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\flastActiveAt\"\xac\x01\n" +
	"\x12RegisterBotRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.paigram.v1.BotTypeR\x04type\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\x12\x1f\n" +
	"\vowner_email\x18\x05 \x01(\tR\n" +
	"ownerEmail\"p\n" +
	"\x13RegisterBotResponse\x12!\n" +
	"\x03bot\x18\x01 \x01(\v2\x0f.paigram.v1.BotR\x03bot\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"api_secret\x18\x03 \x01(\tR\tapiSecret\"I\n" +
	"\x0fBotLoginRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"api_secret\x18\x02 \x01(\tR\tapiSecret\"\xbb\x01\n" +
	"\x10BotLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\x12!\n" +
	"\x03bot\x18\x05 \x01(\v2\x0f.paigram.v1.BotR\x03bot\"=\n" +
	"\x16RefreshBotTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x9f\x01\n" +
	"\x17RefreshBotTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\"<\n" +
	"\x17ValidateBotTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\xa6\x01\n" +
	"\x18ValidateBotTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12!\n" +
	"\x03bot\x18\x02 \x01(\v2\x0f.paigram.v1.BotR\x03bot\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\":\n" +
	"\x15RevokeBotTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"L\n" +
	"\x16RevokeBotTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"*\n" +
	"\x11GetBotInfoRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\"7\n" +
	"\x12GetBotInfoResponse\x12!\n" +
	"\x03bot\x18\x01 \x01(\v2\x0f.paigram.v1.BotR\x03bot*\x8a\x01\n" +
	"\aBotType\x12\x18\n" +
	"\x14BOT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11BOT_TYPE_TELEGRAM\x10\x01\x12\x14\n" +
	"\x10BOT_TYPE_DISCORD\x10\x02\x12\x0f\n" +
	"\vBOT_TYPE_QQ\x10\x03\x12\x13\n" +
	"\x0fBOT_TYPE_WECHAT\x10\x04\x12\x12\n" +
	"\x0eBOT_TYPE_OTHER\x10c*\x89\x01\n" +
	"\tBotStatus\x12\x1a\n" +
	"\x16BOT_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11BOT_STATUS_ACTIVE\x10\x01\x12\x17\n" +
	"\x13BOT_STATUS_INACTIVE\x10\x02\x12\x18\n" +
	"\x14BOT_STATUS_SUSPENDED\x10\x03\x12\x16\n" +
	"\x12BOT_STATUS_REVOKED\x10\x042\x88\x04\n" +
	"\x0eBotAuthService\x12N\n" +
	"\vRegisterBot\x12\x1e.paigram.v1.RegisterBotRequest\x1a\x1f.paigram.v1.RegisterBotResponse\x12E\n" +
	"\bBotLogin\x12\x1b.paigram.v1.BotLoginRequest\x1a\x1c.paigram.v1.BotLoginResponse\x12Z\n" +
	"\x0fRefreshBotToken\x12\".paigram.v1.RefreshBotTokenRequest\x1a#.paigram.v1.RefreshBotTokenResponse\x12]\n" +
	"\x10ValidateBotToken\x12#.paigram.v1.ValidateBotTokenRequest\x1a$.paigram.v1.ValidateBotTokenResponse\x12W\n" +
	"\x0eRevokeBotToken\x12!.paigram.v1.RevokeBotTokenRequest\x1a\".paigram.v1.RevokeBotTokenResponse\x12K\n" +
	"\n" +
	"GetBotInfo\x12\x1d.paigram.v1.GetBotInfoRequest\x1a\x1e.paigram.v1.GetBotInfoResponseB Z\x1epaigram/internal/grpc/pb/v1;pbb\x06proto3"

var (
	file_proto_paigram_v1_bot_auth_proto_rawDescOnce sync.Once
	file_proto_paigram_v1_bot_auth_proto_rawDescData []byte
)

func file_proto_paigram_v1_bot_auth_proto_rawDescGZIP() []byte {
	file_proto_paigram_v1_bot_auth_proto_rawDescOnce.Do(func() {
		file_proto_paigram_v1_bot_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_paigram_v1_bot_auth_proto_rawDesc), len(file_proto_paigram_v1_bot_auth_proto_rawDesc)))
	})
	return file_proto_paigram_v1_bot_auth_proto_rawDescData
}

var file_proto_paigram_v1_bot_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_paigram_v1_bot_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_paigram_v1_bot_auth_proto_goTypes = []any{
	(BotType)(0),                     // 0: paigram.v1.BotType
	(BotStatus)(0),                   // 1: paigram.v1.BotStatus
	(*Bot)(nil),                      // 2: paigram.v1.Bot
	(*RegisterBotRequest)(nil),       // 3: paigram.v1.RegisterBotRequest
	(*RegisterBotResponse)(nil),      // 4: paigram.v1.RegisterBotResponse
	(*BotLoginRequest)(nil),          // 5: paigram.v1.BotLoginRequest
	(*BotLoginResponse)(nil),         // 6: paigram.v1.BotLoginResponse
	(*RefreshBotTokenRequest)(nil),   // 7: paigram.v1.RefreshBotTokenRequest
	(*RefreshBotTokenResponse)(nil),  // 8: paigram.v1.RefreshBotTokenResponse
	(*ValidateBotTokenRequest)(nil),  // 9: paigram.v1.ValidateBotTokenRequest
	(*ValidateBotTokenResponse)(nil), // 10: paigram.v1.ValidateBotTokenResponse
	(*RevokeBotTokenRequest)(nil),    // 11: paigram.v1.RevokeBotTokenRequest
	(*RevokeBotTokenResponse)(nil),   // 12: paigram.v1.RevokeBotTokenResponse
	(*GetBotInfoRequest)(nil),        // 13: paigram.v1.GetBotInfoRequest
	(*GetBotInfoResponse)(nil),       // 14: paigram.v1.GetBotInfoResponse
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
}
var file_proto_paigram_v1_bot_auth_proto_depIdxs = []int32{
	0,  // 0: paigram.v1.Bot.type:type_name -> paigram.v1.BotType
	1,  // 1: paigram.v1.Bot.status:type_name -> paigram.v1.BotStatus
	15, // 2: paigram.v1.Bot.created_at:type_name -> google.protobuf.Timestamp
	15, // 3: paigram.v1.Bot.updated_at:type_name -> google.protobuf.Timestamp
	15, // 4: paigram.v1.Bot.last_active_at:type_name -> google.protobuf.Timestamp
	0,  // 5: paigram.v1.RegisterBotRequest.type:type_name -> paigram.v1.BotType
	2,  // 6: paigram.v1.RegisterBotResponse.bot:type_name -> paigram.v1.Bot
	2,  // 7: paigram.v1.BotLoginResponse.bot:type_name -> paigram.v1.Bot
	2,  // 8: paigram.v1.ValidateBotTokenResponse.bot:type_name -> paigram.v1.Bot
	15, // 9: paigram.v1.ValidateBotTokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 10: paigram.v1.GetBotInfoResponse.bot:type_name -> paigram.v1.Bot
	3,  // 11: paigram.v1.BotAuthService.RegisterBot:input_type -> paigram.v1.RegisterBotRequest
	5,  // 12: paigram.v1.BotAuthService.BotLogin:input_type -> paigram.v1.BotLoginRequest
	7,  // 13: paigram.v1.BotAuthService.RefreshBotToken:input_type -> paigram.v1.RefreshBotTokenRequest
	9,  // 14: paigram.v1.BotAuthService.ValidateBotToken:input_type -> paigram.v1.ValidateBotTokenRequest
	11, // 15: paigram.v1.BotAuthService.RevokeBotToken:input_type -> paigram.v1.RevokeBotTokenRequest
	13, // 16: paigram.v1.BotAuthService.GetBotInfo:input_type -> paigram.v1.GetBotInfoRequest
	4,  // 17: paigram.v1.BotAuthService.RegisterBot:output_type -> paigram.v1.RegisterBotResponse
	6,  // 18: paigram.v1.BotAuthService.BotLogin:output_type -> paigram.v1.BotLoginResponse
	8,  // 19: paigram.v1.BotAuthService.RefreshBotToken:output_type -> paigram.v1.RefreshBotTokenResponse
	10, // 20: paigram.v1.BotAuthService.ValidateBotToken:output_type -> paigram.v1.ValidateBotTokenResponse
	12, // 21: paigram.v1.BotAuthService.RevokeBotToken:output_type -> paigram.v1.RevokeBotTokenResponse
	14, // 22: paigram.v1.BotAuthService.GetBotInfo:output_type -> paigram.v1.GetBotInfoResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_paigram_v1_bot_auth_proto_init() }
func file_proto_paigram_v1_bot_auth_proto_init() {
	if File_proto_paigram_v1_bot_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_paigram_v1_bot_auth_proto_rawDesc), len(file_proto_paigram_v1_bot_auth_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_paigram_v1_bot_auth_proto_goTypes,
		DependencyIndexes: file_proto_paigram_v1_bot_auth_proto_depIdxs,
		EnumInfos:         file_proto_paigram_v1_bot_auth_proto_enumTypes,
		MessageInfos:      file_proto_paigram_v1_bot_auth_proto_msgTypes,
	}.Build()
	File_proto_paigram_v1_bot_auth_proto = out.File
	file_proto_paigram_v1_bot_auth_proto_goTypes = nil
	file_proto_paigram_v1_bot_auth_proto_depIdxs = nil
}
