// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.1
// source: proto/paigram/v1/bot_auth.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BotAuthService_RegisterBot_FullMethodName      = "/paigram.v1.BotAuthService/RegisterBot"
	BotAuthService_BotLogin_FullMethodName         = "/paigram.v1.BotAuthService/BotLogin"
	BotAuthService_RefreshBotToken_FullMethodName  = "/paigram.v1.BotAuthService/RefreshBotToken"
	BotAuthService_ValidateBotToken_FullMethodName = "/paigram.v1.BotAuthService/ValidateBotToken"
	BotAuthService_RevokeBotToken_FullMethodName   = "/paigram.v1.BotAuthService/RevokeBotToken"
	BotAuthService_GetBotInfo_FullMethodName       = "/paigram.v1.BotAuthService/GetBotInfo"
)

// BotAuthServiceClient is the client API for BotAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Bot 认证服务
type BotAuthServiceClient interface {
	// Bot 注册
	RegisterBot(ctx context.Context, in *RegisterBotRequest, opts ...grpc.CallOption) (*RegisterBotResponse, error)
	// Bot 登录（获取访问令牌）
	BotLogin(ctx context.Context, in *BotLoginRequest, opts ...grpc.CallOption) (*BotLoginResponse, error)
	// 刷新访问令牌
	RefreshBotToken(ctx context.Context, in *RefreshBotTokenRequest, opts ...grpc.CallOption) (*RefreshBotTokenResponse, error)
	// 验证 Bot 令牌
	ValidateBotToken(ctx context.Context, in *ValidateBotTokenRequest, opts ...grpc.CallOption) (*ValidateBotTokenResponse, error)
	// 撤销 Bot 令牌
	RevokeBotToken(ctx context.Context, in *RevokeBotTokenRequest, opts ...grpc.CallOption) (*RevokeBotTokenResponse, error)
	// 获取 Bot 信息
	GetBotInfo(ctx context.Context, in *GetBotInfoRequest, opts ...grpc.CallOption) (*GetBotInfoResponse, error)
}

type botAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBotAuthServiceClient(cc grpc.ClientConnInterface) BotAuthServiceClient {
	return &botAuthServiceClient{cc}
}

func (c *botAuthServiceClient) RegisterBot(ctx context.Context, in *RegisterBotRequest, opts ...grpc.CallOption) (*RegisterBotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterBotResponse)
	err := c.cc.Invoke(ctx, BotAuthService_RegisterBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botAuthServiceClient) BotLogin(ctx context.Context, in *BotLoginRequest, opts ...grpc.CallOption) (*BotLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotLoginResponse)
	err := c.cc.Invoke(ctx, BotAuthService_BotLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botAuthServiceClient) RefreshBotToken(ctx context.Context, in *RefreshBotTokenRequest, opts ...grpc.CallOption) (*RefreshBotTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshBotTokenResponse)
	err := c.cc.Invoke(ctx, BotAuthService_RefreshBotToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botAuthServiceClient) ValidateBotToken(ctx context.Context, in *ValidateBotTokenRequest, opts ...grpc.CallOption) (*ValidateBotTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateBotTokenResponse)
	err := c.cc.Invoke(ctx, BotAuthService_ValidateBotToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botAuthServiceClient) RevokeBotToken(ctx context.Context, in *RevokeBotTokenRequest, opts ...grpc.CallOption) (*RevokeBotTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeBotTokenResponse)
	err := c.cc.Invoke(ctx, BotAuthService_RevokeBotToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botAuthServiceClient) GetBotInfo(ctx context.Context, in *GetBotInfoRequest, opts ...grpc.CallOption) (*GetBotInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBotInfoResponse)
	err := c.cc.Invoke(ctx, BotAuthService_GetBotInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotAuthServiceServer is the server API for BotAuthService service.
// All implementations must embed UnimplementedBotAuthServiceServer
// for forward compatibility.
//
// Bot 认证服务
type BotAuthServiceServer interface {
	// Bot 注册
	RegisterBot(context.Context, *RegisterBotRequest) (*RegisterBotResponse, error)
	// Bot 登录（获取访问令牌）
	BotLogin(context.Context, *BotLoginRequest) (*BotLoginResponse, error)
	// 刷新访问令牌
	RefreshBotToken(context.Context, *RefreshBotTokenRequest) (*RefreshBotTokenResponse, error)
	// 验证 Bot 令牌
	ValidateBotToken(context.Context, *ValidateBotTokenRequest) (*ValidateBotTokenResponse, error)
	// 撤销 Bot 令牌
	RevokeBotToken(context.Context, *RevokeBotTokenRequest) (*RevokeBotTokenResponse, error)
	// 获取 Bot 信息
	GetBotInfo(context.Context, *GetBotInfoRequest) (*GetBotInfoResponse, error)
	mustEmbedUnimplementedBotAuthServiceServer()
}

// UnimplementedBotAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBotAuthServiceServer struct{}

func (UnimplementedBotAuthServiceServer) RegisterBot(context.Context, *RegisterBotRequest) (*RegisterBotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterBot not implemented")
}
func (UnimplementedBotAuthServiceServer) BotLogin(context.Context, *BotLoginRequest) (*BotLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BotLogin not implemented")
}
func (UnimplementedBotAuthServiceServer) RefreshBotToken(context.Context, *RefreshBotTokenRequest) (*RefreshBotTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshBotToken not implemented")
}
func (UnimplementedBotAuthServiceServer) ValidateBotToken(context.Context, *ValidateBotTokenRequest) (*ValidateBotTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateBotToken not implemented")
}
func (UnimplementedBotAuthServiceServer) RevokeBotToken(context.Context, *RevokeBotTokenRequest) (*RevokeBotTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeBotToken not implemented")
}
func (UnimplementedBotAuthServiceServer) GetBotInfo(context.Context, *GetBotInfoRequest) (*GetBotInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBotInfo not implemented")
}
func (UnimplementedBotAuthServiceServer) mustEmbedUnimplementedBotAuthServiceServer() {}
func (UnimplementedBotAuthServiceServer) testEmbeddedByValue()                        {}

// UnsafeBotAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotAuthServiceServer will
// result in compilation errors.
type UnsafeBotAuthServiceServer interface {
	mustEmbedUnimplementedBotAuthServiceServer()
}

func RegisterBotAuthServiceServer(s grpc.ServiceRegistrar, srv BotAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedBotAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BotAuthService_ServiceDesc, srv)
}

func _BotAuthService_RegisterBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAuthServiceServer).RegisterBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAuthService_RegisterBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAuthServiceServer).RegisterBot(ctx, req.(*RegisterBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotAuthService_BotLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAuthServiceServer).BotLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAuthService_BotLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAuthServiceServer).BotLogin(ctx, req.(*BotLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotAuthService_RefreshBotToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshBotTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAuthServiceServer).RefreshBotToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAuthService_RefreshBotToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAuthServiceServer).RefreshBotToken(ctx, req.(*RefreshBotTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotAuthService_ValidateBotToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateBotTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAuthServiceServer).ValidateBotToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAuthService_ValidateBotToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAuthServiceServer).ValidateBotToken(ctx, req.(*ValidateBotTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotAuthService_RevokeBotToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeBotTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAuthServiceServer).RevokeBotToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAuthService_RevokeBotToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAuthServiceServer).RevokeBotToken(ctx, req.(*RevokeBotTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotAuthService_GetBotInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAuthServiceServer).GetBotInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAuthService_GetBotInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAuthServiceServer).GetBotInfo(ctx, req.(*GetBotInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BotAuthService_ServiceDesc is the grpc.ServiceDesc for BotAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BotAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paigram.v1.BotAuthService",
	HandlerType: (*BotAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterBot",
			Handler:    _BotAuthService_RegisterBot_Handler,
		},
		{
			MethodName: "BotLogin",
			Handler:    _BotAuthService_BotLogin_Handler,
		},
		{
			MethodName: "RefreshBotToken",
			Handler:    _BotAuthService_RefreshBotToken_Handler,
		},
		{
			MethodName: "ValidateBotToken",
			Handler:    _BotAuthService_ValidateBotToken_Handler,
		},
		{
			MethodName: "RevokeBotToken",
			Handler:    _BotAuthService_RevokeBotToken_Handler,
		},
		{
			MethodName: "GetBotInfo",
			Handler:    _BotAuthService_GetBotInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/paigram/v1/bot_auth.proto",
}
