// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: bot_access.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BotAccessService_ResolveBotUser_FullMethodName         = "/paigram.v1.BotAccessService/ResolveBotUser"
	BotAccessService_LinkPlatformAccount_FullMethodName    = "/paigram.v1.BotAccessService/LinkPlatformAccount"
	BotAccessService_ListAccessibleAccounts_FullMethodName = "/paigram.v1.BotAccessService/ListAccessibleAccounts"
	BotAccessService_IssueServiceTicket_FullMethodName     = "/paigram.v1.BotAccessService/IssueServiceTicket"
)

// BotAccessServiceClient is the client API for BotAccessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BotAccessServiceClient interface {
	ResolveBotUser(ctx context.Context, in *ResolveBotUserRequest, opts ...grpc.CallOption) (*ResolveBotUserResponse, error)
	LinkPlatformAccount(ctx context.Context, in *LinkPlatformAccountRequest, opts ...grpc.CallOption) (*LinkPlatformAccountResponse, error)
	ListAccessibleAccounts(ctx context.Context, in *ListAccessibleAccountsRequest, opts ...grpc.CallOption) (*ListAccessibleAccountsResponse, error)
	IssueServiceTicket(ctx context.Context, in *IssueServiceTicketRequest, opts ...grpc.CallOption) (*IssueServiceTicketResponse, error)
}

type botAccessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBotAccessServiceClient(cc grpc.ClientConnInterface) BotAccessServiceClient {
	return &botAccessServiceClient{cc}
}

func (c *botAccessServiceClient) ResolveBotUser(ctx context.Context, in *ResolveBotUserRequest, opts ...grpc.CallOption) (*ResolveBotUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveBotUserResponse)
	err := c.cc.Invoke(ctx, BotAccessService_ResolveBotUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botAccessServiceClient) LinkPlatformAccount(ctx context.Context, in *LinkPlatformAccountRequest, opts ...grpc.CallOption) (*LinkPlatformAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkPlatformAccountResponse)
	err := c.cc.Invoke(ctx, BotAccessService_LinkPlatformAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botAccessServiceClient) ListAccessibleAccounts(ctx context.Context, in *ListAccessibleAccountsRequest, opts ...grpc.CallOption) (*ListAccessibleAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAccessibleAccountsResponse)
	err := c.cc.Invoke(ctx, BotAccessService_ListAccessibleAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botAccessServiceClient) IssueServiceTicket(ctx context.Context, in *IssueServiceTicketRequest, opts ...grpc.CallOption) (*IssueServiceTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueServiceTicketResponse)
	err := c.cc.Invoke(ctx, BotAccessService_IssueServiceTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotAccessServiceServer is the server API for BotAccessService service.
// All implementations must embed UnimplementedBotAccessServiceServer
// for forward compatibility.
type BotAccessServiceServer interface {
	ResolveBotUser(context.Context, *ResolveBotUserRequest) (*ResolveBotUserResponse, error)
	LinkPlatformAccount(context.Context, *LinkPlatformAccountRequest) (*LinkPlatformAccountResponse, error)
	ListAccessibleAccounts(context.Context, *ListAccessibleAccountsRequest) (*ListAccessibleAccountsResponse, error)
	IssueServiceTicket(context.Context, *IssueServiceTicketRequest) (*IssueServiceTicketResponse, error)
	mustEmbedUnimplementedBotAccessServiceServer()
}

// UnimplementedBotAccessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBotAccessServiceServer struct{}

func (UnimplementedBotAccessServiceServer) ResolveBotUser(context.Context, *ResolveBotUserRequest) (*ResolveBotUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveBotUser not implemented")
}
func (UnimplementedBotAccessServiceServer) LinkPlatformAccount(context.Context, *LinkPlatformAccountRequest) (*LinkPlatformAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkPlatformAccount not implemented")
}
func (UnimplementedBotAccessServiceServer) ListAccessibleAccounts(context.Context, *ListAccessibleAccountsRequest) (*ListAccessibleAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAccessibleAccounts not implemented")
}
func (UnimplementedBotAccessServiceServer) IssueServiceTicket(context.Context, *IssueServiceTicketRequest) (*IssueServiceTicketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueServiceTicket not implemented")
}
func (UnimplementedBotAccessServiceServer) mustEmbedUnimplementedBotAccessServiceServer() {}
func (UnimplementedBotAccessServiceServer) testEmbeddedByValue()                          {}

// UnsafeBotAccessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotAccessServiceServer will
// result in compilation errors.
type UnsafeBotAccessServiceServer interface {
	mustEmbedUnimplementedBotAccessServiceServer()
}

func RegisterBotAccessServiceServer(s grpc.ServiceRegistrar, srv BotAccessServiceServer) {
	// If the following call panics, it indicates UnimplementedBotAccessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BotAccessService_ServiceDesc, srv)
}

func _BotAccessService_ResolveBotUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveBotUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAccessServiceServer).ResolveBotUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAccessService_ResolveBotUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAccessServiceServer).ResolveBotUser(ctx, req.(*ResolveBotUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotAccessService_LinkPlatformAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkPlatformAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAccessServiceServer).LinkPlatformAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAccessService_LinkPlatformAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAccessServiceServer).LinkPlatformAccount(ctx, req.(*LinkPlatformAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotAccessService_ListAccessibleAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccessibleAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAccessServiceServer).ListAccessibleAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAccessService_ListAccessibleAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAccessServiceServer).ListAccessibleAccounts(ctx, req.(*ListAccessibleAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotAccessService_IssueServiceTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueServiceTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotAccessServiceServer).IssueServiceTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotAccessService_IssueServiceTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotAccessServiceServer).IssueServiceTicket(ctx, req.(*IssueServiceTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BotAccessService_ServiceDesc is the grpc.ServiceDesc for BotAccessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BotAccessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paigram.v1.BotAccessService",
	HandlerType: (*BotAccessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveBotUser",
			Handler:    _BotAccessService_ResolveBotUser_Handler,
		},
		{
			MethodName: "LinkPlatformAccount",
			Handler:    _BotAccessService_LinkPlatformAccount_Handler,
		},
		{
			MethodName: "ListAccessibleAccounts",
			Handler:    _BotAccessService_ListAccessibleAccounts_Handler,
		},
		{
			MethodName: "IssueServiceTicket",
			Handler:    _BotAccessService_IssueServiceTicket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bot_access.proto",
}
