CREATE TABLE IF NOT EXISTS audit_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(64) NOT NULL,
    actor_type VARCHAR(32) NOT NULL,
    actor_user_id BIGINT UNSIGNED NULL,
    action VARCHAR(128) NOT NULL,
    target_type VARCHAR(64) NULL,
    target_id VARCHAR(191) NULL,
    binding_id BIGINT UNSIGNED NULL,
    result VARCHAR(32) NOT NULL,
    reason_code VARCHAR(64) NULL,
    request_id VARCHAR(128) NULL,
    ip VARCHAR(128) NULL,
    user_agent VARCHAR(512) NULL,
    metadata_json JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_audit_events_category (category),
    KEY idx_audit_events_actor_type (actor_type),
    KEY idx_audit_events_actor_user_id (actor_user_id),
    KEY idx_audit_events_action (action),
    KEY idx_audit_events_target_type (target_type),
    KEY idx_audit_events_target_id (target_id),
    KEY idx_audit_events_binding_id (binding_id),
    KEY idx_audit_events_result (result),
    KEY idx_audit_events_reason_code (reason_code),
    KEY idx_audit_events_request_id (request_id),
    KEY idx_audit_events_created_at (created_at),
    CONSTRAINT fk_audit_events_actor_user FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_audit_events_binding FOREIGN KEY (binding_id) REFERENCES platform_account_bindings(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
