package config

import (
	"fmt"
	"strings"
	"sync"
	"time"

	"github.com/spf13/viper"
	"go.uber.org/zap"

	"paigram/internal/logging"
)

// Config aggregates application configuration sections.
type Config struct {
	App       AppConfig       `mapstructure:"app"`
	Database  DatabaseConfig  `mapstructure:"database"`
	Auth      AuthConfig      `mapstructure:"auth"`
	Frontend  FrontendConfig  `mapstructure:"frontend"`
	Redis     RedisConfig     `mapstructure:"redis"`
	GRPC      GRPCConfig      `mapstructure:"grpc"`
	RateLimit RateLimitConfig `mapstructure:"rate_limit"`
	Email     EmailConfig     `mapstructure:"email"`
	Security  SecurityConfig  `mapstructure:"security"`
	Sentry    SentryConfig    `mapstructure:"sentry"`
}

// FrontendConfig holds settings describing the user-facing frontend that
// receives links generated by this service (password reset, email
// verification, magic-link callbacks, etc.).
//
// BaseURL MUST be set in production. It is intentionally NOT derived from
// any request header (e.g. Origin/Referer/Host) because attacker-controlled
// headers would let a malicious caller redirect password-reset links to
// their own domain, leading to credential phishing. See V2 hardening.
type FrontendConfig struct {
	// BaseURL is the canonical externally-reachable URL of the frontend,
	// e.g. "https://app.example.com". Trailing slashes are normalized.
	BaseURL string `mapstructure:"base_url"`
}

// AppConfig holds HTTP server configuration.
type AppConfig struct {
	Name           string     `mapstructure:"name"`
	Host           string     `mapstructure:"host"`
	Port           int        `mapstructure:"port"`
	Mode           string     `mapstructure:"mode"`
	TrustedProxies []string   `mapstructure:"trusted_proxies"` // Trusted proxy CIDR ranges for X-Forwarded-For
	RealIPHeader   string     `mapstructure:"real_ip_header"`  // Custom header for real IP (e.g., "CF-Connecting-IP")
	IPv6Subnet     int        `mapstructure:"ipv6_subnet"`     // IPv6 subnet prefix length for rate limiting (default: 64)
	CORS           CORSConfig `mapstructure:"cors"`
}

// CORSConfig holds HTTP CORS configuration.
type CORSConfig struct {
	Enabled             bool     `mapstructure:"enabled"`
	AllowOrigins        []string `mapstructure:"allow_origins"`
	AllowMethods        []string `mapstructure:"allow_methods"`
	AllowHeaders        []string `mapstructure:"allow_headers"`
	ExposeHeaders       []string `mapstructure:"expose_headers"`
	AllowCredentials    bool     `mapstructure:"allow_credentials"`
	AllowWildcard       bool     `mapstructure:"allow_wildcard"`
	AllowPrivateNetwork bool     `mapstructure:"allow_private_network"`
	MaxAgeSeconds       int      `mapstructure:"max_age"`
}

// DatabaseConfig holds MySQL connection configuration.
type DatabaseConfig struct {
	Addr          string `mapstructure:"addr"`
	Username      string `mapstructure:"username"`
	Password      string `mapstructure:"password"`
	Dbname        string `mapstructure:"dbname"`
	Config        string `mapstructure:"config"`
	MigrationsDir string `mapstructure:"migrations_dir"`
	MaxIdleConns  int    `mapstructure:"max_idle_conns"`
	MaxOpenConns  int    `mapstructure:"max_open_conns"`
	LogMode       string `mapstructure:"log_mode"`
	LogZap        bool   `mapstructure:"log_zap"`
	SlowThreshold int    `mapstructure:"slow_threshold"`
	AutoMigrate   bool   `mapstructure:"auto_migrate"`
	AutoSeed      bool   `mapstructure:"auto_seed"`
}

// AuthConfig holds configuration for authentication flows.
type AuthConfig struct {
	AccessTokenTTLSeconds         int                            `mapstructure:"access_token_ttl"`
	RefreshTokenTTLSeconds        int                            `mapstructure:"refresh_token_ttl"`
	SessionUpdateAgeSeconds       int                            `mapstructure:"session_update_age"` // Auto-refresh threshold
	SessionFreshAgeSeconds        int                            `mapstructure:"session_fresh_age"`  // Freshness requirement for sensitive ops
	EmailVerificationTTLSeconds   int                            `mapstructure:"email_verification_ttl"`
	OAuthStateTTLSeconds          int                            `mapstructure:"oauth_state_ttl"`
	AllowedOAuthProviders         []string                       `mapstructure:"allowed_providers"`
	OAuthProviders                map[string]OAuthProviderConfig `mapstructure:"oauth"`
	DefaultOAuthRedirectURL       string                         `mapstructure:"default_oauth_redirect_url"`
	MaxConcurrentSessionsPerUser  int                            `mapstructure:"max_sessions_per_user"`
	PendingUserExpirySeconds      int                            `mapstructure:"pending_user_expiry"`
	PasswordResetTokenTTLSeconds  int                            `mapstructure:"password_reset_ttl"`
	RequireEmailVerificationLogin bool                           `mapstructure:"require_verified_email_login"`
	ServiceTicketTTLSeconds       int                            `mapstructure:"service_ticket_ttl"`
	ServiceTicketIssuer           string                         `mapstructure:"service_ticket_issuer"`
	ServiceTicketSigningKey       string                         `mapstructure:"service_ticket_signing_key"`
	Captcha                       AuthCaptchaConfig              `mapstructure:"captcha"`
}

// AuthCaptchaConfig holds CAPTCHA configuration for auth flows.
type AuthCaptchaConfig struct {
	Turnstile TurnstileConfig `mapstructure:"turnstile"`
}

// TurnstileConfig holds Cloudflare Turnstile verification settings.
type TurnstileConfig struct {
	Enabled                   bool   `mapstructure:"enabled"`
	SiteKey                   string `mapstructure:"site_key"`
	SecretKey                 string `mapstructure:"secret_key"`
	VerifyURL                 string `mapstructure:"verify_url"`
	ExpectedHostname          string `mapstructure:"expected_hostname"`
	RequireOnRegister         bool   `mapstructure:"require_on_register"`
	RequireOnLogin            bool   `mapstructure:"require_on_login"`
	LoginFailureThreshold     int    `mapstructure:"login_failure_threshold"`
	LoginFailureWindowSeconds int    `mapstructure:"login_failure_window"`
	RequestTimeoutSeconds     int    `mapstructure:"request_timeout"`
}

// OAuthProviderConfig models third-party provider credentials.
//
// Issuer and JWKSURL are required for OIDC providers (Google, etc.) so that
// id_tokens can be cryptographically verified. They are intentionally not
// inferred from the AuthURL — providers do not consistently expose a
// discoverable OIDC config and we never want to fall back to an unverified
// path. If a deployment forgets to configure these for a non-Telegram
// provider, OIDC verification will fail closed at runtime.
type OAuthProviderConfig struct {
	ClientID     string   `mapstructure:"client_id"`
	ClientSecret string   `mapstructure:"client_secret"`
	RedirectURL  string   `mapstructure:"redirect_url"`
	AuthURL      string   `mapstructure:"auth_url"`
	TokenURL     string   `mapstructure:"token_url"`
	UserInfoURL  string   `mapstructure:"user_info_url"`
	Issuer       string   `mapstructure:"issuer"`
	JWKSURL      string   `mapstructure:"jwks_url"`
	Scopes       []string `mapstructure:"scopes"`
}

// RedisConfig holds Redis connection and pooling behaviour.
type RedisConfig struct {
	Enabled      bool   `mapstructure:"enabled"`
	Addr         string `mapstructure:"addr"`
	Username     string `mapstructure:"username"`
	Password     string `mapstructure:"password"`
	DB           int    `mapstructure:"db"`
	Prefix       string `mapstructure:"prefix"`
	DialTimeout  int    `mapstructure:"dial_timeout"`
	ReadTimeout  int    `mapstructure:"read_timeout"`
	WriteTimeout int    `mapstructure:"write_timeout"`
	PoolSize     int    `mapstructure:"pool_size"`
	MinIdleConns int    `mapstructure:"min_idle_conns"`
	MaxRetries   int    `mapstructure:"max_retries"`
}

// GRPCConfig holds gRPC server configuration.
type GRPCConfig struct {
	Enabled               bool `mapstructure:"enabled"`
	Port                  int  `mapstructure:"port"`
	MaxConnectionIdle     int  `mapstructure:"max_connection_idle"`
	MaxConnectionAge      int  `mapstructure:"max_connection_age"`
	MaxConnectionAgeGrace int  `mapstructure:"max_connection_age_grace"`
	KeepAliveTime         int  `mapstructure:"keepalive_time"`
	KeepAliveTimeout      int  `mapstructure:"keepalive_timeout"`
}

// RateLimitConfig holds rate limiting configuration.
type RateLimitConfig struct {
	Enabled bool                `mapstructure:"enabled"`
	Auth    RateLimitAuthConfig `mapstructure:"auth"`
	API     RateLimitAPIConfig  `mapstructure:"api"`
}

// RateLimitAuthConfig holds rate limits for authentication endpoints.
type RateLimitAuthConfig struct {
	Login        string `mapstructure:"login"`
	Register     string `mapstructure:"register"`
	VerifyEmail  string `mapstructure:"verify_email"`
	RefreshToken string `mapstructure:"refresh_token"`
	OAuth        string `mapstructure:"oauth"`
}

// RateLimitAPIConfig holds rate limits for API endpoints.
type RateLimitAPIConfig struct {
	Authenticated   string `mapstructure:"authenticated"`
	Unauthenticated string `mapstructure:"unauthenticated"`
}

// EmailConfig holds email service configuration.
type EmailConfig struct {
	Enabled       bool   `mapstructure:"enabled"`
	Provider      string `mapstructure:"provider"`      // smtp, sendgrid, mailgun, etc.
	SMTPHost      string `mapstructure:"smtp_host"`     // e.g., smtp.gmail.com
	SMTPPort      int    `mapstructure:"smtp_port"`     // e.g., 587
	SMTPUsername  string `mapstructure:"smtp_username"` // e.g., user@example.com
	SMTPPassword  string `mapstructure:"smtp_password"`
	FromEmail     string `mapstructure:"from_email"`     // Sender email address
	FromName      string `mapstructure:"from_name"`      // Sender name
	UseTLS        bool   `mapstructure:"use_tls"`        // Use TLS
	UseAsyncQueue bool   `mapstructure:"use_async"`      // Enable async sending queue
	QueueBackend  string `mapstructure:"queue_backend"`  // Queue backend: "memory" or "redis" (default: memory)
	QueueSize     int    `mapstructure:"queue_size"`     // Queue size for async sending
	Timeout       int    `mapstructure:"timeout"`        // SMTP timeout in seconds
	RetryAttempts int    `mapstructure:"retry_attempts"` // Number of retry attempts
	RetryDelay    int    `mapstructure:"retry_delay"`    // Delay between retries in seconds
	TemplateDir   string `mapstructure:"template_dir"`   // Directory for email templates (optional, uses embedded if empty)
}

// SecurityConfig holds security-related configuration.
type SecurityConfig struct {
	SuspiciousLoginDetection  bool          `mapstructure:"suspicious_login_detection"`   // Enable suspicious login detection
	SuspiciousLoginEmailAlert bool          `mapstructure:"suspicious_login_email_alert"` // Send email alerts for suspicious logins
	SecuritySettingsURL       string        `mapstructure:"security_settings_url"`        // URL to account security settings page
	BcryptCost                int           `mapstructure:"bcrypt_cost"`                  // Bcrypt hashing cost (default: 12, min: 10, max: 31)
	RequireRedisFor2FA        bool          `mapstructure:"require_redis_for_2fa"`        // V22: when true, 2FA rate limiting fails closed if Redis is unavailable
	TwoFAFailClosedTTL        time.Duration `mapstructure:"twofa_fail_closed_ttl"`        // V22: lock duration applied when failing closed; defaults to 1m
}

// SentryConfig holds Sentry error reporting configuration.
type SentryConfig struct {
	Enabled          bool    `mapstructure:"enabled"`
	DSN              string  `mapstructure:"dsn"`
	Environment      string  `mapstructure:"environment"`
	Release          string  `mapstructure:"release"`
	Debug            bool    `mapstructure:"debug"`
	AttachStacktrace bool    `mapstructure:"attach_stacktrace"`
	SampleRate       float64 `mapstructure:"sample_rate"`
	TracesSampleRate float64 `mapstructure:"traces_sample_rate"`
	FlushTimeout     int     `mapstructure:"flush_timeout"`
}

var (
	cfg     *Config
	cfgOnce sync.Once
)

// Load initializes configuration using Viper and returns a singleton instance.
// Subsequent calls reuse the loaded configuration.
func Load(paths ...string) (*Config, error) {
	var err error
	cfgOnce.Do(func() {
		v := viper.New()
		v.SetConfigName("config")
		v.SetConfigType("yaml")

		setDefaults(v)

		if len(paths) == 0 {
			v.AddConfigPath(".")
			v.AddConfigPath("./config")
			v.AddConfigPath("./configs")
		} else {
			for _, path := range paths {
				v.AddConfigPath(path)
			}
		}

		v.SetEnvPrefix("PAI")
		v.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
		v.AutomaticEnv()

		if readErr := v.ReadInConfig(); readErr != nil {
			err = fmt.Errorf("read config: %w", readErr)
			return
		}

		localCfg := &Config{}
		if unmarshalErr := v.Unmarshal(localCfg); unmarshalErr != nil {
			err = fmt.Errorf("unmarshal config: %w", unmarshalErr)
			return
		}
		if validateErr := validateServiceTicketConfig(localCfg); validateErr != nil {
			err = validateErr
			return
		}
		warnIfFrontendBaseURLMissing(localCfg)
		warnIfVerificationEmailDispatchMissing(localCfg)

		cfg = localCfg
	})

	if err != nil {
		Reset()
		return nil, err
	}

	if cfg == nil {
		return nil, fmt.Errorf("configuration not loaded")
	}
	return cfg, nil
}

func validateServiceTicketConfig(cfg *Config) error {
	if cfg == nil {
		return fmt.Errorf("configuration not loaded")
	}
	auth := cfg.Auth
	if auth.ServiceTicketTTLSeconds <= 0 {
		return fmt.Errorf("auth.service_ticket_ttl must be greater than zero")
	}
	if auth.ServiceTicketIssuer == "" {
		return fmt.Errorf("auth.service_ticket_issuer must not be empty")
	}
	if auth.ServiceTicketSigningKey == "" {
		return nil
	}
	if len(auth.ServiceTicketSigningKey) < 32 {
		return fmt.Errorf("auth.service_ticket_signing_key must be at least 32 bytes when configured")
	}
	return nil
}

// warnIfFrontendBaseURLMissing logs a warning when frontend.base_url is
// empty. We deliberately do NOT fail Load here — operators may run admin
// commands or migrations without a frontend, and breaking those flows over
// a missing URL would be hostile. The runtime password-reset path is
// already fail-closed: if BaseURL is empty it skips email send entirely
// (see V2 hardening in handler/auth/password_reset.go).
func warnIfFrontendBaseURLMissing(cfg *Config) {
	if cfg == nil {
		return
	}
	if strings.TrimSpace(cfg.Frontend.BaseURL) != "" {
		return
	}
	logging.Warn(
		"frontend.base_url is not configured; password-reset and similar emails will be suppressed",
		zap.String("setting", "frontend.base_url"),
	)
}

// warnIfVerificationEmailDispatchMissing covers a deployment-blocking
// gap surfaced by V14: the registration handler stores a hashed
// verification token but does not yet dispatch the verification email
// containing the plaintext token (see handler/auth/email.go::
// RegisterEmail KNOWN GAP). Until that wiring lands, an operator who
// turns on auth.require_verified_email_login=true will lock all new
// users out of login because there is no path by which a freshly
// registered user can obtain the plaintext token. We log a loud
// warning rather than failing Load: existing deployments with
// require_verified_email_login=false are unaffected, and operators
// using OAuth-only login should not be blocked from starting.
//
// This warning will become a hard validation error once the
// verification email dispatch is wired up; remove this function then.
func warnIfVerificationEmailDispatchMissing(cfg *Config) {
	if cfg == nil {
		return
	}
	if !cfg.Auth.RequireEmailVerificationLogin {
		return
	}
	logging.Warn(
		"auth.require_verified_email_login=true but the registration handler does not dispatch verification emails yet; "+
			"newly registered email-password users will be unable to log in until verification email dispatch is wired up. "+
			"See KNOWN GAP in internal/handler/auth/email.go::RegisterEmail.",
		zap.String("setting", "auth.require_verified_email_login"),
	)
}

// MustLoad panics when configuration cannot be loaded.
func MustLoad(paths ...string) *Config {
	c, err := Load(paths...)
	if err != nil {
		panic(err)
	}
	return c
}

// Reset clears the Singleton (useful for tests).
func Reset() {
	cfg = nil
	cfgOnce = sync.Once{}
}

func setDefaults(v *viper.Viper) {
	// App defaults
	v.SetDefault("app.trusted_proxies", []string{
		"127.0.0.1",      // localhost
		"10.0.0.0/8",     // private network
		"172.16.0.0/12",  // Docker default network
		"192.168.0.0/16", // private network
	})
	v.SetDefault("app.real_ip_header", "") // Empty means use X-Forwarded-For via TrustedProxies
	v.SetDefault("app.ipv6_subnet", 64)    // /64 subnet (typical home/business allocation)
	v.SetDefault("app.cors.enabled", false)
	v.SetDefault("app.cors.allow_methods", []string{"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"})
	v.SetDefault("app.cors.allow_headers", []string{"Origin", "Content-Type", "Accept", "Authorization"})
	v.SetDefault("app.cors.expose_headers", []string{})
	v.SetDefault("app.cors.allow_credentials", false)
	v.SetDefault("app.cors.allow_wildcard", false)
	v.SetDefault("app.cors.allow_private_network", false)
	v.SetDefault("app.cors.max_age", 43200)

	v.SetDefault("database.config", "charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai")
	v.SetDefault("database.migrations_dir", "initialize/migrate/sql")
	v.SetDefault("database.max_idle_conns", 10)
	v.SetDefault("database.max_open_conns", 100)
	v.SetDefault("database.log_mode", "info")
	v.SetDefault("database.log_zap", true)
	v.SetDefault("database.slow_threshold", 1000)
	v.SetDefault("database.auto_migrate", true)
	v.SetDefault("database.auto_seed", true)

	v.SetDefault("auth.access_token_ttl", 900)
	v.SetDefault("auth.refresh_token_ttl", 604800)
	v.SetDefault("auth.email_verification_ttl", 86400)
	v.SetDefault("auth.oauth_state_ttl", 300)
	v.SetDefault("auth.allowed_providers", []string{"github", "google", "telegram"})
	v.SetDefault("auth.default_oauth_redirect_url", "http://localhost:8080/api/v1/auth/oauth/callback")
	v.SetDefault("auth.max_sessions_per_user", 10)
	v.SetDefault("auth.pending_user_expiry", 2592000)
	v.SetDefault("auth.password_reset_ttl", 3600)
	v.SetDefault("auth.require_verified_email_login", true)
	v.SetDefault("auth.service_ticket_ttl", 300)
	v.SetDefault("auth.service_ticket_issuer", "paigram-account-center")
	v.SetDefault("auth.service_ticket_signing_key", "")
	v.SetDefault("auth.captcha.turnstile.enabled", false)
	v.SetDefault("auth.captcha.turnstile.verify_url", "https://challenges.cloudflare.com/turnstile/v0/siteverify")
	v.SetDefault("auth.captcha.turnstile.require_on_register", true)
	v.SetDefault("auth.captcha.turnstile.require_on_login", false)
	v.SetDefault("auth.captcha.turnstile.login_failure_threshold", 3)
	v.SetDefault("auth.captcha.turnstile.login_failure_window", 900)
	v.SetDefault("auth.captcha.turnstile.request_timeout", 5)

	// Frontend defaults: empty BaseURL by design — production deployments
	// must override this via config or env (PAI_FRONTEND_BASE_URL). Leaving
	// it empty causes the password-reset path to log + skip email rather
	// than fall back to an attacker-controlled Origin header. See V2.
	v.SetDefault("frontend.base_url", "")

	v.SetDefault("redis.enabled", false)
	v.SetDefault("redis.addr", "127.0.0.1:6379")
	v.SetDefault("redis.db", 0)
	v.SetDefault("redis.prefix", "paigram")
	v.SetDefault("redis.dial_timeout", 5)
	v.SetDefault("redis.read_timeout", 3)
	v.SetDefault("redis.write_timeout", 3)
	v.SetDefault("redis.pool_size", 20)
	v.SetDefault("redis.min_idle_conns", 5)
	v.SetDefault("redis.max_retries", 2)

	v.SetDefault("rate_limit.enabled", true)
	v.SetDefault("rate_limit.auth.login", "5-M")
	v.SetDefault("rate_limit.auth.register", "3-H")
	v.SetDefault("rate_limit.auth.verify_email", "10-H")
	v.SetDefault("rate_limit.auth.refresh_token", "10-M")
	v.SetDefault("rate_limit.auth.oauth", "10-M")
	v.SetDefault("rate_limit.api.authenticated", "1000-H")
	v.SetDefault("rate_limit.api.unauthenticated", "100-H")

	v.SetDefault("email.enabled", false)
	v.SetDefault("email.provider", "smtp")
	v.SetDefault("email.smtp_host", "smtp.gmail.com")
	v.SetDefault("email.smtp_port", 587)
	v.SetDefault("email.from_email", "noreply@paigram.com")
	v.SetDefault("email.from_name", "PaiGram")
	v.SetDefault("email.use_tls", true)
	v.SetDefault("email.use_async", true)
	v.SetDefault("email.retry_attempts", 3)
	v.SetDefault("email.retry_delay", 5)

	v.SetDefault("security.bcrypt_cost", 12)
	v.SetDefault("security.suspicious_login_detection", false)
	v.SetDefault("security.suspicious_login_email_alert", false)
	// V22: fail closed by default. Operators who run a single instance
	// without Redis can opt out by setting require_redis_for_2fa: false.
	v.SetDefault("security.require_redis_for_2fa", true)
	v.SetDefault("security.twofa_fail_closed_ttl", "1m")

	v.SetDefault("sentry.enabled", false)
	v.SetDefault("sentry.dsn", "")
	v.SetDefault("sentry.environment", "development")
	v.SetDefault("sentry.release", "")
	v.SetDefault("sentry.debug", false)
	v.SetDefault("sentry.attach_stacktrace", true)
	v.SetDefault("sentry.sample_rate", 1.0)
	v.SetDefault("sentry.traces_sample_rate", 0.0)
	v.SetDefault("sentry.flush_timeout", 2)
}

// GetBcryptCost returns the bcrypt cost with validation
// Returns a safe value between 10 and 14 (default: 12)
func (c *Config) GetBcryptCost() int {
	cost := c.Security.BcryptCost
	if cost < 10 {
		return 12 // Default: OWASP recommended minimum
	}
	if cost > 14 {
		return 14 // Cap at 14 to prevent DoS (14 takes ~1.5 seconds)
	}
	return cost
}
